version: 2.1

jobs:
  inspect:
    parameters:
      img:
        type: string
    docker:
      - image: << parameters.img >>
    resource_class: arm.large
    steps:
      # - checkout
      - run: |
          uname -m
      - run: |
          lsb_release -a

 
workflows:
  main:
    jobs:
      # See https://discuss.circleci.com/t/product-launch-arm-docker-preview/48601
      - inspect:
          matrix:
            parameters:
              img:
                - cimg/base:current
                - cimg/node:20.5.0
                - cimg/node:18.17.0
                - cimg/rust:1.71
                - cimg/openjdk:17.0.8
                - cimg/openjdk:11.0.20
                - cimg/deploy:2023.07.1
                - cimg/aws:2023.07.1
                - cimg/azure:2023.07.1
                
