version: 2.1

jobs:
  inspect:
    parameters:
      img:
        type: string
      resource-class:
        type: string
    docker:
      - image: << parameters.img >>
    resource_class: << parameters.resource-class >>
    steps:
      # - checkout
      - run: |
          uname -m
      - run: |
          lsb_release -a

 
workflows:
  main:
    jobs:
      # See https://discuss.circleci.com/t/product-launch-arm-docker-preview/48601
      - inspect:
          matrix:
            parameters:
              img:
                - cimg/aws:2023.07.1
              resource-class:
                - "arm.large"
                - "large"
                
