version: 2.1

jobs:
  inspect:
    parameters:
      img:
        type: string
    docker:
      - image: << parameters.img >>
    # open preview! https://discuss.circleci.com/t/product-launch-arm-docker-preview/48601
    # note: arm-medium, unlike arm.medium for Linux ARM machine.  
    resource_class: arm.medium
    steps:
      - checkout
      - run: |
          uname -m
      - run: |
          lsb_release -a

 
workflows:
  main:
    jobs:
      - inspect:
          matrix:
            parameters:
              img:
                - cimg/base:current


#                 - ubuntu-2004:202201-01
#                 - ubuntu-2004:202111-02
#                 - ubuntu-2004:202111-01
#                 - ubuntu-2004:202107-01
#                 - ubuntu-2004:202104-01
