version: 2.1

jobs:
  inspect:
    parameters:
      img:
        type: string
    docker:
      - image: << parameters.img >>
    resource_class: arm.medium
    steps:
      # - checkout
      - run: |
          uname -m
      - run: |
          lsb_release -a

 
workflows:
  main:
    jobs:
      - inspect:
          matrix:
            parameters:
              img:
                # - cimg/base:current
                # - bastiandoetsch209/cli-build-arm64:latest
                - cimg/aws:2023.07
#                 - ubuntu-2004:202201-01
#                 - ubuntu-2004:202111-02
#                 - ubuntu-2004:202111-01
#                 - ubuntu-2004:202107-01
#                 - ubuntu-2004:202104-01
