version: 2.1

jobs:
  inspect:
    machine:
      image: arm-default
      # TEST: see if DLC is allowed for ARM
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - run: |
          cat /proc/cpuinfo
          uname -m
      - run: |
          which jq
          file "$(which jq)"
      - run: |
          docker version

  armed:
    parameters:
      dlc:
        type: boolean
        default: true
      img:
        # see https://circleci.com/docs/2.0/using-arm#overview
        type: string
    machine:
      image: << parameters.img >>
      docker_layer_caching: << parameters.dlc >>
      resource_class: arm.medium
    steps:
      - checkout
 
workflows:
  main:
    jobs:
      - inspect
